-- Snowflake Finance Close Business Case (synthetic data only)
-- Purpose: protect the daily sales decision from a replayed order event.
-- Run in a disposable or approved non-production Snowflake account.

USE ROLE SYSADMIN;
CREATE OR REPLACE WAREHOUSE RESCUE_LAB_WH WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;
CREATE OR REPLACE DATABASE RESCUE_LAB_SNOWFLAKE;
CREATE OR REPLACE SCHEMA RESCUE_LAB_SNOWFLAKE.RAW;
CREATE OR REPLACE SCHEMA RESCUE_LAB_SNOWFLAKE.TRUSTED;
CREATE OR REPLACE SCHEMA RESCUE_LAB_SNOWFLAKE.FINANCE;
USE WAREHOUSE RESCUE_LAB_WH;

CREATE OR REPLACE TABLE RESCUE_LAB_SNOWFLAKE.RAW.ORDER_EVENTS (
  ORDER_ID STRING, CUSTOMER_ID STRING, CUSTOMER_NAME STRING, CHANNEL STRING,
  AMOUNT NUMBER(12, 2), EVENT_TS TIMESTAMP_NTZ, INGESTED_AT TIMESTAMP_NTZ
);

INSERT INTO RESCUE_LAB_SNOWFLAKE.RAW.ORDER_EVENTS VALUES
  ('ORD-1041','CUS-01','Amina Rahman','Web',248.00,'2026-09-04 09:00:00','2026-09-04 09:01:00'),
  ('ORD-1042','CUS-02','Daniel Lee','Store',89.50,'2026-09-04 09:05:00','2026-09-04 09:06:00'),
  ('ORD-1043','CUS-03','Siti Nabila','Marketplace',420.00,'2026-09-04 09:10:00','2026-09-04 09:11:00'),
  ('ORD-1043','CUS-03','Siti Nabila','Marketplace',420.00,'2026-09-04 09:10:00','2026-09-04 09:12:00'),
  ('ORD-1044','CUS-04','Kumar Raj','Web',175.20,'2026-09-04 09:15:00','2026-09-04 09:16:00'),
  ('ORD-1045','CUS-05','Mei Chen','Store',64.90,'2026-09-04 09:20:00','2026-09-04 09:21:00');

CREATE OR REPLACE DYNAMIC TABLE RESCUE_LAB_SNOWFLAKE.TRUSTED.ORDERS
  TARGET_LAG = 'DOWNSTREAM'
  WAREHOUSE = RESCUE_LAB_WH
AS
SELECT ORDER_ID, CUSTOMER_ID, CUSTOMER_NAME, CHANNEL, AMOUNT, EVENT_TS, INGESTED_AT
FROM RESCUE_LAB_SNOWFLAKE.RAW.ORDER_EVENTS
WHERE AMOUNT > 0 AND EVENT_TS IS NOT NULL
QUALIFY ROW_NUMBER() OVER (PARTITION BY ORDER_ID ORDER BY INGESTED_AT) = 1;

CREATE OR REPLACE VIEW RESCUE_LAB_SNOWFLAKE.TRUSTED.ORDER_QUARANTINE AS
SELECT ORDER_ID, CUSTOMER_ID, CUSTOMER_NAME, CHANNEL, AMOUNT, EVENT_TS, INGESTED_AT,
  CASE WHEN COUNT(*) OVER (PARTITION BY ORDER_ID) > 1 THEN 'duplicate_order_id' END AS QUARANTINE_REASON
FROM RESCUE_LAB_SNOWFLAKE.RAW.ORDER_EVENTS
QUALIFY ROW_NUMBER() OVER (PARTITION BY ORDER_ID ORDER BY INGESTED_AT DESC) = 1;

CREATE OR REPLACE DYNAMIC TABLE RESCUE_LAB_SNOWFLAKE.FINANCE.DAILY_SALES
  TARGET_LAG = 'DOWNSTREAM'
  WAREHOUSE = RESCUE_LAB_WH
AS
SELECT TO_DATE(EVENT_TS) AS SALES_DATE, CHANNEL, COUNT(*) AS TRUSTED_ORDER_COUNT, SUM(AMOUNT) AS TRUSTED_REVENUE
FROM RESCUE_LAB_SNOWFLAKE.TRUSTED.ORDERS
GROUP BY 1, 2;

-- The Finance reconciliation: 6 received, 5 trusted, RM997.60 reported.
SELECT
  (SELECT COUNT(*) FROM RESCUE_LAB_SNOWFLAKE.RAW.ORDER_EVENTS) AS RAW_EVENTS,
  (SELECT COUNT(*) FROM RESCUE_LAB_SNOWFLAKE.TRUSTED.ORDERS) AS TRUSTED_ORDERS,
  (SELECT SUM(TRUSTED_REVENUE) FROM RESCUE_LAB_SNOWFLAKE.FINANCE.DAILY_SALES) AS TRUSTED_REVENUE;
