-- Illustrative least-privilege model. Replace principals with approved account groups.
USE ROLE SECURITYADMIN;
CREATE OR REPLACE ROLE RESCUE_FINANCE_READER;
CREATE OR REPLACE ROLE RESCUE_OPERATIONS_READER;
CREATE OR REPLACE ROLE RESCUE_AUDITOR;

USE ROLE SYSADMIN;
CREATE OR REPLACE MASKING POLICY RESCUE_LAB_SNOWFLAKE.TRUSTED.CUSTOMER_NAME_MASK AS (VALUE STRING)
  RETURNS STRING -> CASE
    WHEN CURRENT_ROLE() IN ('RESCUE_OPERATIONS_READER') THEN VALUE
    ELSE CONCAT(LEFT(VALUE, 1), '***')
  END;
ALTER TABLE RESCUE_LAB_SNOWFLAKE.TRUSTED.ORDERS MODIFY COLUMN CUSTOMER_NAME
  SET MASKING POLICY RESCUE_LAB_SNOWFLAKE.TRUSTED.CUSTOMER_NAME_MASK;

USE ROLE SECURITYADMIN;
GRANT USAGE ON WAREHOUSE RESCUE_LAB_WH TO ROLE RESCUE_FINANCE_READER;
GRANT USAGE ON DATABASE RESCUE_LAB_SNOWFLAKE TO ROLE RESCUE_FINANCE_READER;
GRANT USAGE ON SCHEMA RESCUE_LAB_SNOWFLAKE.FINANCE TO ROLE RESCUE_FINANCE_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA RESCUE_LAB_SNOWFLAKE.FINANCE TO ROLE RESCUE_FINANCE_READER;

GRANT USAGE ON WAREHOUSE RESCUE_LAB_WH TO ROLE RESCUE_OPERATIONS_READER;
GRANT USAGE ON DATABASE RESCUE_LAB_SNOWFLAKE TO ROLE RESCUE_OPERATIONS_READER;
GRANT USAGE ON SCHEMA RESCUE_LAB_SNOWFLAKE.TRUSTED TO ROLE RESCUE_OPERATIONS_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA RESCUE_LAB_SNOWFLAKE.TRUSTED TO ROLE RESCUE_OPERATIONS_READER;

GRANT USAGE ON WAREHOUSE RESCUE_LAB_WH TO ROLE RESCUE_AUDITOR;
GRANT USAGE ON DATABASE RESCUE_LAB_SNOWFLAKE TO ROLE RESCUE_AUDITOR;
GRANT USAGE ON SCHEMA RESCUE_LAB_SNOWFLAKE.TRUSTED TO ROLE RESCUE_AUDITOR;
GRANT SELECT ON ALL TABLES IN SCHEMA RESCUE_LAB_SNOWFLAKE.TRUSTED TO ROLE RESCUE_AUDITOR;
